### ISSUE TITLE
Uncaught error when grid is rendered

### ISSUE THREAD

**Issue by wwalraven** [syncfusion/ej2-data#3]
Uncaught (in promise) Error: Unauthorized
    at Ajax.stateChange (VM5206 319:69)
    at XMLHttpRequest._this.httpRequest.onreadystatechange (VM5206 319:26)

Server returned 401 as response to DataManager.executeQuery with UrlAdaptor

Render.dataManagerFailure() is called correctly to notify component for actionFailure.

`Ajax.stateChange (ajax.js?5fe7:67)
_this.httpRequest.onreadystatechange (ajax.js?5fe7:24)
XMLHttpRequest.send (async)
(anonymous) (ajax.js?5fe7:32)
Ajax.send (ajax.js?5fe7:22)
DataManager.makeRequest (manager.js?a849:230)
DataManager.executeQuery (manager.js?a849:133)
Data.getData (data.js?3742:128)
Render.refreshDataManager (render.js?b265:65)
Render.render (render.js?b265:42)
Grid.gridRender (grid.js?a1e4:1234)
Grid.render (grid.js?a1e4:560)
Component.appendTo (component.js?3ba1:99)
mounted (Grid.vue?121c:132)
callHook (vue.esm.js?efeb:2868)
insert (vue.esm.js?efeb:4045)
invokeInsertHook (vue.esm.js?efeb:5799)
patch (vue.esm.js?efeb:6018)
Vue._update (vue.esm.js?efeb:2613)
updateComponent (vue.esm.js?efeb:2741)
get (vue.esm.js?efeb:3084)
Watcher (vue.esm.js?efeb:3073)
mountComponent (vue.esm.js?efeb:2745)
Vue$3.$mount (vue.esm.js?efeb:8311)
Vue$3.$mount (vue.esm.js?efeb:10635)
Vue._init (vue.esm.js?efeb:4522)
Vue$3 (vue.esm.js?efeb:4607)
(anonymous) (main.js?1c90:13)
(anonymous) (app.js:2808)
__webpack_require__ (app.js:679)
fn (app.js:89)
(anonymous) (app.js:2697)
__webpack_require__ (app.js:679)
(anonymous) (app.js:725)
(anonymous) (app.js:728)`

**Comment by RamdhasUeikattan** [comment]
Hi wwalraven,

We suspect that this error occurred due to the absence of authentication TOKEN in the Grid request passed to the server. Please use the headers property of the DataManager to add authentication token. Please refer to the below code example

```

let grid: Grid = new Grid({
    dataSource: new DataManager({
            url: ‘. . .',
            crossDomain: true,
            headers: [{ 'AuthKey': 'AuthValue'}]  // adding custom headers
        }),

. . .

});

```
For more information, please refer the below documentation link.

http://ej2.syncfusion.com/15.4.17/documentation/data/howto.html?lang=typescript#adding-custom-headers


Regards,
Ramdhas  Ueikattan

**Comment by wwalraven** [comment]
Hi Ramdhas,

Thank you for your quick response. To clarify: the problem is not that the authentication failed (it is supposed to in this test case). The problem is that Ajax.stateChange's rejection of a promise is not caught in the ej2 framework and an application is not able to catch it since it is apparently swallowed by the rendering code.

The request is send with credentials which happen to be a an expired cookie.

Thank you,
Walt

**Comment by RamdhasUeikattan** [comment]
Hi Walt,

Thanks for your update.

We have validated the problem. The script error arises due to the unhandled failure cases in Promise. We have considered “Uncaught script error in failure ajax request” as a defect and the fix will be available in November last week release.

Regards,
Ramdhas  Ueikattan.

**Comment by dhivyasyncfusion** [comment]
Hi Walt,

Thanks for your patience.

We are glad to announce that our **_v15.4.20-preview_** release is rolled out successfully. In this release, we have added the fix for **“Uncaught error when grid is rendered”** issue.

https://github.com/syncfusion/ej2-data/releases/tag/v15.4.20-preview

Please let us know if you have any queries.

Regards,
R.Dhivya
